version: '3'
services:
  app:
    image: ramdanariadi/sigmatech-cimb:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sigmatech-test
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: secret
    ports:
      - "8080:8080"
    networks:
      - sigmatech-network
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: sigmatech-test
      PGDATA: /var/lib/postgresql/data/blog
    ports:
      - "5432:5432"
    volumes:
      - sigmatech_pgdb_data:/var/lib/postgresql/data/blog
    networks:
      - sigmatech-network

networks:
  sigmatech-network:
    driver: bridge

volumes:
  sigmatech_pgdb_data:
